src/main/java/org/sqlite/JDBC.java
src/test/java/org/sqlite/JDBCTest.java

I don't think any additional checks are required, because the underlying methods will try to establish connection and throw a `SQLException` if it fails, and that is in accordance with the spec.

return null if unhandled url protocol

---

src/main/java/org/sqlite/core/CoreConnection.java

One convenient use of the URL parameters is to specify the date format.  Unfortunately the URL parameter value was aggressively lower-cased which breaks many supplied date formats.  Now you can properly specify a case-sensitive date format.

Fix case-mangling of URL parameters

---

README.md

Looks like David Crawshaw moved hosting for his project to GitHub. Looks a little neater to have a correct link in the README, I think.

Fix link to Zentus' SQLite JDBC driver.

---

.gitignore
src/main/java/org/sqlite/core/CoreConnection.java
src/main/java/org/sqlite/date/DateFormatUtils.java
src/main/java/org/sqlite/date/DateParser.java
src/main/java/org/sqlite/date/DatePrinter.java
src/main/java/org/sqlite/date/ExceptionUtils.java
src/main/java/org/sqlite/date/FastDateFormat.java
src/main/java/org/sqlite/date/FastDateParser.java
src/main/java/org/sqlite/date/FastDatePrinter.java
src/main/java/org/sqlite/date/FormatCache.java
src/main/java/org/sqlite/date/package-info.java
src/main/java/org/sqlite/jdbc3/JDBC3ResultSet.java
src/test/java/org/sqlite/QueryTest.java

SimpleDateFormat's .parse() method does not treat format Strings the same as its .format() method does.  This is a problem when dealing with dates created by ActiveRecord, which stores dates as strings with pseudo-microsecond precision in the following format: `yyyy-MM-dd HH:mm:ss.SSS000` (It's actually stored with millisecond precision, but `000` is always appended to the string.
SimpleDateFormat will properly format a date given this format string, but it fails when trying to parse a date.
The FastDateFormat utility provided by Apache Commons Lang 3.x does not have this issue.  As an added bonus, it is also faster and thread-safe.
This pull request uses FastDateFormat instead of SimpleDateFormat to get around this issue.
Unfortunately, it also has a few drawbacks.
1) make is broken …

Use Apache Commons FastDateFormat instead of SimpleDateFormat

---

src/main/java/org/sqlite/core/CoreResultSet.java
src/main/java/org/sqlite/jdbc3/JDBC3ResultSet.java
src/test/java/org/sqlite/ResultSetTest.java

This is a performance boost when using #findColumn a lot.

Add a cache for ResultSet#findColumn

---

src/main/java/org/sqlite/util/OSInfo.java

On an armhf system with no binutils installed and using a Java prior to version 8, armhf will not be detected and the wrong .so will be unpacked. Unfortunately this results in a crash with a FileNotFoundException, which is confusing (because the file is there and it has the right permissions).
This patch attempts to provide the user with a more meaningful message.

Warning message when readelf is not installed.

---

Makefile.common

Bugfix for this issue: https://bitbucket.org/xerial/sqlite-jdbc/issues/191/problem-with-native-compile-on-windows-x86

Fix the build on 32-bit Windows

---

src/main/java/org/sqlite/jdbc3/JDBC3ResultSet.java

Bugfix for this issue: https://bitbucket.org/xerial/sqlite-jdbc/issues/163/null-pointer-exception-on-null-input

Fix JDBC3ResultSet.getBinaryStream()

---

src/main/java/org/sqlite/core/NativeDB.c
src/main/java/org/sqlite/jdbc3/JDBC3PreparedStatement.java
src/test/java/org/sqlite/PrepStmtTest.java

JNI uses a modified UTF-8 encoding. For supplementary characters, an invalid UTF-8 sequence was written to the database, which resulted in interoperability problems. The solution is to avoid UTF-8 in the native code and use the UTF-16 functions of SQLite (where possible). SQLite will then convert the UTF-16 to standards-compliant, unmodified UTF-8.
This also fixes related bugs in JDBC3PreparedStatement and improves the "out of memory" handling in the native code.
Fixed Issues:
- https://bitbucket.org/xerial/sqlite-jdbc/issues/200/wrong-utf-8-decoding-of-unicode-code , same as https://github.com/xerial/sqlite-jdbc/issues/61
- https://bitbucket.org/xerial/sqlite-jdbc/issues/144/nativedbexec-throws-an-exception-without
- https://bitbucket.org/xerial/sqlite-jdbc/issues/84/bug-in-nativedbc-bind …

Fix the handling of supplementary characters (characters > U+FFFF)

---

src/main/java/org/sqlite/core/CoreStatement.java
src/main/java/org/sqlite/core/DB.java
src/main/java/org/sqlite/jdbc3/JDBC3PreparedStatement.java
src/main/java/org/sqlite/jdbc3/JDBC3Statement.java
src/test/java/org/sqlite/TransactionTest.java

Right now, if execute(String) fails when a transaction is open, then you aren't able to ever roll back the transaction and start again. Replacing "execute" with "executeUpdate" makes the problem go away.
I'm not 100% convinced my fix is right here, but it does make the test pass!

Test and fix bug in execute(String sql)

---

src/main/java/org/sqlite/jdbc3/JDBC3ResultSet.java

JDBC3ResultSet.isSigned(int) does now return true if the type of the
column is either "NUMERIC", "INTEGER" or "REAL". In all other cases it
returns false.

Implemented JDBC3ResultSet.isSigned(int).

---

src/main/java/org/sqlite/SQLiteErrorCode.java
src/main/java/org/sqlite/SQLiteException.java
src/main/java/org/sqlite/core/CoreStatement.java
src/main/java/org/sqlite/core/DB.java
src/main/java/org/sqlite/core/NativeDB.c
src/test/java/org/sqlite/AllTests.java
src/test/java/org/sqlite/ErrorMessageTest.java

Enable extended error code reporting in sqlite, and new error enum values in SQLiteErrorCode.java. The extended error code is held in a new member of SQLiteErrorCode, so that the code member retains its old behaviour, so that  existing clients which depend on that are not affected. The message returned by toString does however change for errors for which there now are more detailed descriptions.

Use extended error codes

---

src/main/java/org/sqlite/core/NativeDB.c
src/main/java/org/sqlite/core/NativeDB.java
src/test/java/org/sqlite/StatementTest.java

Also don't use modified UTF-8, see https://github.com/xerial/sqlite-jdbc/issues/61
Convert Java Strings to "unmodified" UTF-8 and vice versa.
Improve out-of-memory handling.
Fixes https://github.com/xerial/sqlite-jdbc/issues/78

Use UTF-8 functions of SQLite to avoid unexpected data type conversions

---

src/test/java/org/sqlite/AllTests.java
src/test/java/org/sqlite/JSON1Test.java

This pull request builds on #123 and enables the JSON1 extension with unit tests for SQLite JSON functions introduced in 3.9.x.

Enable the JSON1 extension

---

src/main/java/org/sqlite/core/CorePreparedStatement.java
src/main/java/org/sqlite/jdbc3/JDBC3PreparedStatement.java
src/test/java/org/sqlite/PrepStmtTest.java

Currently, calling `addBatch()` on a prepared statement where the query has no parameters causes a NullPointerException. This PR fixes that.
Of course calling `addBatch()` this way is not very useful when using JDBC directly, but can occur in higher-level wrapper libraries that don't special-case the zero parameters case.
Other JDBC drivers (I checked MySQL and PostgreSQL) work just fine even when there are no parameters in the query. The JDBC spec doesn't mention this case specifically.
This probably also fixes #48. There is still no error thrown when some parameters are missing (and there probably should be), but that was the case before as well.

Fix crash on addBatch with zero-parameter queries

---

src/main/ext/extension-functions.c

The preprocessor variable _SQLITEINT_H_ was renamed to SQLITEINT_H
with SQLite 3.14.0 (http://www.sqlite.org/src/info/5471aca0158851d3).
Only if neither is defined attempt to include sqliteInt.h.

Fix build problem for SQLite 3.14.0 onwards

---

src/main/java/org/sqlite/core/DB.java
src/main/java/org/sqlite/core/NativeDB.c
src/main/java/org/sqlite/core/NativeDB.java

re: https://github.com/xerial/sqlite-jdbc/issues/160
On my MacBook Pro,
**3.8.11.2**
> Time to create & insert: 6872 ms
> Time to select: 8963 ms
> Time to select & get resultset values: 10279 ms
**3.14.2**
> Time to create & insert: 6654 ms
> Time to select: 11362 ms
> Time to select & get resultset values: 14068 ms
> 
**3.14.2.1-SNAPSHOT**
> Time to create & insert: 6527 ms
> Time to select: 8942 ms
> Time to select & get resultset values: 10936 ms
>

seems to make the latest code faster by reducing the back-n-forth between JNI and Java.

---

src/main/java/org/sqlite/jdbc3/JDBC3DatabaseMetaData.java
src/test/java/org/sqlite/DBMetaDataTest.java

If expression is used instead of column, then null-name is returned by sqlite

fixed NPE in getIndexInfo() for expression index

---

src/main/java/org/sqlite/Function.java
src/main/java/org/sqlite/core/DB.java
src/main/java/org/sqlite/core/NativeDB.c
src/main/java/org/sqlite/core/NativeDB.java

Pass Strings as UTF-8 byte arrays between the Java code and the native library
to improve the performance.
Also remove the declaration of value_bytes(), because this function has never
been implemented in the native code.
See https://github.com/xerial/sqlite-jdbc/pull/162

Reduce the back-n-forth between JNI and Java even more

---

src/main/java/org/sqlite/core/DB.java
src/test/java/org/sqlite/PrepStmtTest.java

Similar to #166, but for `executeUpdate()`

Check if pointer is valid before call to reset()

---

src/main/java/org/sqlite/jdbc3/JDBC3DatabaseMetaData.java
src/test/java/org/sqlite/DBMetaDataTest.java

Adds columns `IS_AUTOINCREMENT` and `IS_GENERATEDCOLUMN` to `DatabaseMetadata#getColumns` to comply with JDBC 4.1, fixing #132 .
NOTE: This implementation currently does not handle `PRIMARY KEYs` as auto-incremented.

Extend DatabaseMetadata#getColumns

---

src/main/java/org/sqlite/SQLiteJDBCLoader.java

I'm using sqlite-jdbc with windows and I have a big problem with #80.
As this is a bug in JVM (not able to delete On Exit dlls that were loaded) I added another file beside the extracted dll with the same name and the suffix ".lck". 
The file is correctly deleted on JVM exit. So now I can very easy create a cleanup method looking for all sqlite dll with missing lck-file and delete them in custom code.
Other ways (like looking if file is locked) was not always solving the problem (with multiple JVM-processes (e.g. 20)). 
(Maybe a cleanup method should also be added)
Maybe this would be useful for other people.
What do you think.

Added Lck-File that is correctly deleted on JVM-Exit.

---

src/main/java/org/sqlite/jdbc3/JDBC3Connection.java

Added simpliest implimentation of typeMap getter and setter in order to avoid senseless exceptions. When some methods in snaq.db need to get typeMap to clean it up in connection pool, they call getTypeMap method. And it causes senseless crash, because they don't use content of this map, they just destroy it.

TypeMap implimentation added

---

Makefile
docker/Dockerfile.alpine-linux_x86_64

In my project I'm using Alpine docker java image.
Alpine is using libc instead of glibc, which gives these errors:
> [22:07:23 WARN]: Failed to load native library:sqlite-3.15.1-fb339d95-503e-4709-89aa-514bc537aa5c-libsqlitejdbc.so. osinfo: Linux/x86_64
[22:07:23 WARN]: java.lang.UnsatisfiedLinkError: /tmp/sqlite-3.15.1-fb339d95-503e-4709-89aa-514bc537aa5c-libsqlitejdbc.so: Error relocating /tmp/sqlite-3.15.1-fb339d95-503e-4709-89aa-514bc537aa5c-libsqlitejdbc.so: __isnan: symbol not found
[22:07:23 WARN]: java.lang.UnsatisfiedLinkError: org.sqlite.core.NativeDB._open_utf8([BI)V
[22:07:23 WARN]: 	at org.sqlite.core.NativeDB._open_utf8(Native Method)
[22:07:23 WARN]: 	at org.sqlite.core.NativeDB._open(NativeDB.java:71)
[22:07:23 WARN]: 	at org.sqlite.core.DB.open(DB.java:174)
[22:07:23 …

Adding docker build for Alpine Linux

---

src/test/java/org/sqlite/BusyHandlerTest.java

Sometimes this test failed randomly on my machine. Since it used `assertEquals` it was not possible to determine what the difference was.

BusyHandlerTest: use assertEquals instead of assertTrue

---

Makefile

Since the sqlite.org supports ssl it would make sense to use that when downloading the zip archives.

makefile: use ssl for downloads from sqlite.org

---

src/main/java/org/sqlite/SQLiteJDBCLoader.java
src/test/java/org/sqlite/SQLiteJDBCLoaderTest.java

We faced this problem running a few instances of app that use sqlite. Creating lock-file before lib allows to avoid concurrent creating/deleting on initializing. Test taken from @bertmaher 's repo, reproduces on MacOS 10.12.5. Extra tested on Win10

Fix issue #197: create lock before lib file, remove lib files by absolute path

---

.gitignore
src/main/java/org/sqlite/jdbc3/JDBC3DatabaseMetaData.java
src/test/java/org/sqlite/DBMetaDataTest.java

Removed unnecessary `toLowerCase()` when obtaining primary keys, and also added unit tests for mixed case primary key names.

Fixes case-sensitivity of primary keys - see issue #219

---

README.md
README_BUILD.md

Update README and build instructions to point to Github Issues instead of BitBucket Issues - fixes #242

Update README and build instructions to point to Github Issues instead of BitBucket Issues - fixes #242

---

src/main/java/org/sqlite/SQLiteJDBCLoader.java
src/main/java/org/sqlite/core/NativeDB.c

see issue #267 ; I found a more elegant, less intrusive solution.
I change the global refs to weak global refs. Since these references are
all to class objects, they will be referenced by the classloader
and not go away too early. But they won't keep the classes from becoming unreachable.
I verified, that this solves the problem
with this test:
[test.txt](https://github.com/xerial/sqlite-jdbc/files/1289555/test.txt)
Before the change, I get 10 instances of each sqlite related class in memory, after I get none.
The local tests during build (32bit Linux only) yield no errors.

Fix for class gc memory leak

---

src/main/java/org/sqlite/SQLiteJDBCLoader.java

Additional fix for issue #197 ; lock file needs to created before lib file. Otherwise the cleanup might see lib file, but not lock file, delete the lib file, and then the check starting with
InputStream extractedLibIn = new FileInputStream(extractedLibFile);
might fail.

Additional fix for issue #197

---

src/main/java/org/sqlite/jdbc3/JDBC3DatabaseMetaData.java
src/test/java/org/sqlite/DBMetaDataTest.java

DatabaseMetaData getImportedKeys does not return primary keys or foreign key names bug - fixes #280

DatabaseMetaData getImportedKeys does not return primary keys or foreign key names bug - #280

---

src/main/java/org/sqlite/SQLiteConfig.java

This PR adds support for encrypted databases. 
Most encrypted database drivers configure there password via ```pragma key='abc'``` or ```pragma hexkey='AF..'```.
This change calls the ```pragma hexkey``` and a following verification statement, if a password is provided.
This is usefull if you provide a custom libary via:
```
-Dorg.sqlite.lib.path=.
-Dorg.sqlite.lib.name=sqlite_cryption_support.dll
```

Add support for encrypted databases

---

pom.xml

since SQLFeatureNotSupportedException is documented to only be available since 1.6
https://docs.oracle.com/javase/7/docs/api/java/sql/SQLFeatureNotSupportedException.html

change compiler source version to 1.6

---

src/main/java/org/sqlite/core/CorePreparedStatement.java
src/main/java/org/sqlite/jdbc3/JDBC3PreparedStatement.java
src/test/java/org/sqlite/PrepStmtTest.java

please have a look at the commit messages for explanation
the current implementation does not verify that all parameters for the prepared
statement are set
I also front loaded the check into addBatch since once a statement/command is added it becomes immutable so therefore it doesn't make any sense to wait till execution for that check.
this allows to keep the memory of the bitset constant == paramCount since we only need to validate
the current statement/command since previous statements/commands are guaranteed ot be valid

Fix prepared statement parameter handling

---

src/main/java/org/sqlite/core/CoreResultSet.java
src/test/java/org/sqlite/ResultSetTest.java

Fixes #349
From profiling our app in production we noticed that our finalizer thread was periodically waiting on the synchronized lock on the DB (introduced in #215).  By the time our ResultSet hits the finalizer queue the ResultSet has already been closed, so there's no need to acquire the lock to reset the statement pointer.  As part of this I've removed what I believe to be dead code around checking for the nullability of the stmt member on the ResultSet.

Skip synchronized block in close() if ResultSet is already closed

---

src/main/java/org/sqlite/jdbc4/JDBC4ResultSet.java
src/test/java/org/sqlite/QueryTest.java

The position was used as the starting index and the length as the end index. It's wrong according to the specification. The first argument is the start position. It starts with 1. The second argument is the length. The length must be greater than -1.

Implement Clob.getSubString() according to the jdbc specification

---

src/main/java/org/sqlite/SQLiteConfig.java
src/main/java/org/sqlite/SQLiteConnectionConfig.java
src/main/java/org/sqlite/SQLiteDataSource.java
src/test/java/org/sqlite/TransactionTest.java

The misspelled DEFFERED is still accepted for backwards compatibility.
Fixes #316

Fix spelling of TransactionMode.DEFERRED (#316)

---

src/test/java/org/sqlite/BusyHandlerTest.java
src/test/java/org/sqlite/SQLiteJDBCLoaderTest.java
src/test/java/org/sqlite/TransactionTest.java

* BusyHandlerTest should now be deterministic.
* Removed BusyHandlerTest.testInterrupt as it probably didn't test
what it was supposed to. The other two tests should be enough.
(The "expected" SQLException was a "query does not return ResultSet"
error because of executeQuery for insert instead of execute.)
* More verification in SQLiteJDBCLoaderTest.
* Make tests faster (run all tests in less than 2s instead of 20s).

Fix some tests

---

src/main/java/org/sqlite/JDBC.java
src/main/java/org/sqlite/SQLiteConnection.java

When no database is specified, SQLite is supposed to create a [temporary database](https://www.sqlite.org/inmemorydb.html#temp_db), i.e. residing in memory but able to be flushed to disk under
memory pressure.
Actually, the driver forces SQLite to open an in-memory database
instead. These databases cannot be flushed to disk and might come out of
memory.

Support temporary databases with no file name

---

src/main/java/org/sqlite/core/NativeDB.c
src/test/java/org/sqlite/ErrorMessageTest.java

Creating a pull request of the patch for #382 in the hope of increasing its priority.
The fix always sets the database handle immediately after opening the database and simply clears it just after the `throwex_errorcode` call on failures, avoiding the issue that the `errmsg` call triggered by `throwex_errorcode` requires a valid database handle to be set, which is not true for the call in `_open_utf8` without this change.
Additionally a test is added that verifies that the correct more specific SQLite error message is returned when opening the database fails.

Fix issue #382: Wrong error message when open fails

---

Makefile

javah has been superseded by the -h option added to javac in JDK 8.
The tool javah.exe was removed in Java 10.
(https://stackoverflow.com/questions/50352098/javah-missing-after-jdk-install)
Also clean output files generated by javac -h.
With this patch I was able to build with JDK 8 and JDK 11.
CI fails for JDK 7 — is it worth supporting that?

Update build process for JDK 10 (javah removal)

---

Makefile
src/test/java/org/sqlite/ExtensionTest.java

If SQLite has been augmented with JDBC extensions add a compile option
which can be queried from the 'compile_options' pragma.
This makes it possible to determine at runtime whether the client supports
customs functions or not.

Add compile option 'JDBC_EXTENSIONS'

---

README.md

Maven repository now requires HTTPS.  Fixed Maven URLs to be HTTPS

Fixed Maven URLs to be HTTPS

---

Makefile
docker/Dockerfile.alpine-linux_x86_64
src/main/java/org/sqlite/util/OSInfo.java

Please have a look at our extension that make the resulting jar files also work in an Alpine Linux container.
Changes:
- Changed to name of the compile SQLite binary when compiling for Alpine (as not to conflict with normal x86_64 linux)
- Added a small function in OSInfo.java that determines whether the code is running in an Alpine environment and uses the corresponding SQLite binary if this is the case.
Looking forward to your comments!

Add Alpine support

---

src/main/java/org/sqlite/core/CorePreparedStatement.java
src/main/java/org/sqlite/jdbc3/JDBC3PreparedStatement.java
src/test/java/org/sqlite/PrepStmtTest.java

This fixes #393. This is correct/safe for a few reasons:
- Un-bound parameters are okay. sqlite interprets unbound parameters as `null` (near the bottom here: https://www.sqlite.org/c3ref/bind_blob.html).
- With this update, un-bound parameters in this library will be bound as null, but this is also okay because (see above) that's equivalent to binding null.
- This matches the implementations of other drivers:
-- requery/sqlite-android: https://github.com/requery/sqlite-android/blob/da119c1aa926975330ff727067fedc93e49da5f2/sqlite-android/src/main/java/io/requery/android/database/sqlite/SQLiteConnection.java#L1028
-- Android SQLite: https://android.googlesource.com/platform/frameworks/base/+/master/core/java/android/database/sqlite/SQLiteConnection.java#1088
Worst case, this defers to …

Remove sparse index checks

---

src/main/java/org/sqlite/jdbc3/JDBC3DatabaseMetaData.java

There are two instances of Strings being directly inserted into queries executed on the database without escaping. This can potentially lead to vulnerabilities or crashes. Adds the two necessary `escape` calls.

Add missing calls to "escape"

---

src/main/java/org/sqlite/core/DB.java
src/test/java/org/sqlite/PrepStmtTest.java

Prior to 37278d1, extended result codes were preserved when throwing a
SQLiteException. This restores that behavior.
Refs #343

Preserve extended result codes in SQLiteException

---

src/main/java/org/sqlite/core/CorePreparedStatement.java
src/main/java/org/sqlite/jdbc3/JDBC3ResultSet.java
src/main/java/org/sqlite/jdbc3/JDBC3Statement.java

This PR is to fix #217.  Overriding finalize() on these 3 classes actually causes memory leak since the finalize() method adds a reference to the JVM Finalizer and this prevents the objects from garbage collection until the System finalization is invoked by the JVM.  So it is actually counter productive of having these method overridden for attempting to clean up resources; and not to say that, it's an anti-pattern in Java of overriding finalize() for the exact reason it's stated.
Also, these classes already have the close() method implemented, so callers should call close() to release resource and that's how JDBC [Statement](https://docs.oracle.com/javase/8/docs/api/java/sql/Statement.html#close--) and [ResultSet](https://docs.oracle.com/javase/8/docs/api/java/sql/ResultSet.html#close--) …

Remove Override OBject.finalize in Statement and ResultSet

---

src/main/java/org/sqlite/util/OSInfo.java

I am on Ubuntu 20, openJdk 14.0.2,
I am using sqlite from Apache Netbeans with Gradle 6.7
When debugging, isAlpine() kind of always blocks, not sure why. Sometimes it does not block.
When emitting "cat /etc/os-release | grep ^ID" to console in ubuntu, there is no problem, works as excepted.
When running, also sometimes blocks, sometimes runs.
I am wondering if it is a problem with openJdk.
Shortly before getConnection, I delete  the database file with File.deleteIfExists !?
ANYHOW: Having a timeout here is a small improvement. It adds stability.

adding timeout to OSInfo::isAlpine

---

src/main/java/org/sqlite/util/OSInfo.java

This code path probably never worked. `uname -m` returns a value terminated by a newline, so the comparison never worked. Even if it did, it would have returned `arm64`, which is not a valid folder name for the native library.
Why it may have worked on `aarch64` systems is that after that failed comparison, it would detect the JVM and find out it's `armv7`, which is compatible with `arm64`, so probably went unnoticed.

fix aarch64 detection

---

src/main/java/org/sqlite/SQLiteConnection.java
src/main/java/org/sqlite/jdbc3/JDBC3ResultSet.java
src/main/java/org/sqlite/jdbc3/JDBC3Statement.java
src/test/java/org/sqlite/ReadUncommittedTest.java
src/test/java/org/sqlite/StatementTest.java

Should fix #515 and #546 
* Connection.setTransactionIsolation - promote isolation levels READ_COMMITTED and REPEATABLE_READ, which are not natively supported by SQLite, to SERIALIZABLE. The driver should accept all four values as long as it can substitute a higher isolation level than the one requested.
* Statement.setFetchDirection - while SQLite does not act on the fetch direction hint, it should accept the call so long as the argument is valid.
In both of these cases, spec-compliance makes it easier to write driver-agnostic user code.
ResultSet.setFetchDirection was not changed, because the current impl is actually correct. It is correct because SQLite only allows FORWARD_ONLY ResultSets.

Improve Compliance With JDBC Specifications

---

src/main/java/org/sqlite/core/NativeDB.java

Profiling this has revealed it's faster to just use the String decoding methods vs the ByteBuffer decoding methods.  This adds a copy back to the process of getting data out of SQLite but it removes the JNI allocation (my original issue).

Don't use ByteBuffer decode() - slower

---

src/main/java/org/sqlite/date/FastDateParser.java
src/test/java/org/sqlite/StatementTest.java

This pull request fixes the bug described by issue https://github.com/xerial/sqlite-jdbc/issues/88
This bug can be reproduced by using `ResultSet.getDate()` to parse a `DATETIME` created using `CURRENT_TIMESTAMP`
The exception thrown will look something like this:
`java.text.ParseException: Unparseable date: "2021-06-08 02:00:47" does not match (\p{Nd}++)\Q-\E(\p{Nd}++)\Q-\E(\p{Nd}++)\Q \E(\p{Nd}++)\Q:\E(\p{Nd}++)\Q:\E(\p{Nd}++)\Q.\E(\p{Nd}++)`
The regex used to parse dates does not account for the fact that new dates created by SQLite's `CURRENT_TIMESTAMP` do not include millisecond information. The regex used by the date parser tries to find a string matching `yyyy-MM-dd HH:mm:ss.SSS` but the dates created by SQLite do not include the milliseconds `.SSS` so the date strings are not …

Normalize source string when parsing

---

src/main/java/org/sqlite/SQLiteJDBCLoader.java
src/test/java/org/sqlite/SQLiteJDBCLoaderTest.java

This changes makes it so that we replace` Class#getResourceAsStream()` with a custom method that finds the resources and creates a stream but disables caching the stream. This is necessary in environments with where the native library has to be extracted and used with multiple class loaders that get closed.
Specifically, I was observing the following [JDK-8205976](https://bugs.openjdk.java.net/browse/JDK-8205976) in a [Gradle](https://gradle.org/) project with concurrent tasks that use sqlite-jdbc. The exact exception I was observing was:
```
java.io.IOException: Stream closed
at java.base/java.util.zip.InflaterInputStream.ensureOpen(InflaterInputStream.java:68)
at java.base/java.util.zip.InflaterInputStream.read(InflaterInputStream.java:143)
at …
```

Avoid using shared resource streams between class loaders when extracting the native library.

---

src/main/java/org/sqlite/date/FastDateParser.java
src/test/java/org/sqlite/StatementTest.java

Reverts xerial/sqlite-jdbc#609 because of test failure

Revert "Normalize source string when parsing"

---

pom.xml
src/main/resources/META-INF/native-image/org.xerial/sqlite-jdbc/jni-config.json
src/main/resources/META-INF/native-image/org.xerial/sqlite-jdbc/native-image.properties
src/main/resources/META-INF/native-image/org.xerial/sqlite-jdbc/reflect-config.json

Hello,
Following [this recommended way](https://www.graalvm.org/reference-manual/native-image/BuildConfiguration/#embedding-a-configuration-file) from Oracle's Graalvm, this should make it easier for others that want to use sqlite-jdbc in a native-image compiled with GraalVM, this way users don't need to add those configs manually as GraalVM will find it in the classpath if using sqlite-jdbc lib.
[This](https://github.com/ericdallo/sqlite-graalvm-sample) is a sample showing that config works
I was using [this lib](https://github.com/ericdallo/sqlite-jni-graal-fix) in other projects to fix those missing configs, but after compiling it in json correctly now it's possible to bring those configs to sqlite-jdbc to make it available to everyone, if this PR get merged, that lib could be …

[graalvm] Add necessary config for graalvm native-image compilation

---

Makefile

`make linux-ppc64` would fail following changes in https://github.com/dockcross/dockcross/commit/4ac8689b5f91f95e5b54d704f8a810df24dc37e5

fix Linux PPC64 build failing because of recent dockcross changes

---

Makefile
docker/dockcross-armv6

Following the fix done in https://github.com/dockcross/dockcross/pull/510 we can bring back armv6 support
It would be good if someone with a Raspberry PI with armv6 could test this.
Closes #583

bring back armv6 support

---

Makefile
Makefile.common

This uses [empterdose/freebsd-cross-build:9.3](https://github.com/MrDOS/freebsd-cross-build) to compile for FreeBSD x86 and x86_64. This has been tested via Komga by some of our users and reported to work well.
Note that dockcross doesn't support any FreeBSD build.
I thought about creating a derived Docker image that would have `bash`, `java` and `perl` installed, but given the frequency of rebuilds this is probably overkill.
Supersedes #494

Add FreeBSD x86 and x86_64 native library cross-compilation via Docker

---

.github/workflows/test.yml
src/test/java/org/sqlite/SQLiteJDBCLoaderTest.java

- converts the github workflow to use the matrix notation for Linux tests
- run tests on Windows and MacOS
- fix some tests failing on Windows (`SQLiteJDBCLoaderTest.multipleClassLoader`)
You can see a sample execution here: https://github.com/gotson/sqlite-jdbc/actions/runs/1150032640 (edit: or in the checks of this very PR)

CI tests for Windows and MacOS

---

Makefile

These control whether to run docker in interactive mode and attach the tty,
but may prohibit to run the build in CI environments where no tty is available
(e.g. Jenkins).

Makefile: remove `-it`/`-ti` flags from docker calls

---

Makefile
Makefile.common

- update cross prefix for Linux arm64, following recent dockcross changes. see: https://github.com/dockcross/dockcross/pull/547/files#diff-c54899d03cb7216b8fd1f26f7d3596963d167b8954f83c9c26f33d9d4b84470aR19
- update strip for Linux Android arm, following recent dockcross changes. see: dockcross/dockcross#570 and dockcross/dockcross#568
- simplify the cross prefix, as the binaries are available in the PATH

Update cross prefix following recent dockcross updates

---

.github/workflows/test.yml

I think the existing cache action was not doing anything, but i am not sure. The new v2 action has built-in caching for maven dependencies, this should speed up the builds.

migrate Github Actions to setup-java@v2 with built-in maven cache

---

.github/workflows/test.yml

The AdoptOpenJDK has been discontinued since July 2021. When using Zulu you get all the latest updated (TCK Tested) builds for all versions of OpenJDK. Also added fixed (major) versions to the list of JDKs to build. This is good practice when customers or vendors are at fixed versions in production and using the latest can / has broken. If the fixed version is green (passed) and the latest is red (test failed) that means it isn’t your code that broke, but the latest build was the cause of the issue. 
As AdoptOpenJDK -> Adoptium -> Eclipse Foundation has suggested Temurin builds (which also are nice TCK tested builds) they do not support every version of OpenJDK such as many non-LTS versions and fixed version prior to july/aug 2021.

Using TCK Tested JDK builds & fixed versions of OpenJDK

---

src/main/java/org/sqlite/SQLiteJDBCLoader.java

Use of setDefaultUseCaches impacts all URLClassLoaders and HttpURLConnections, which can lead to erratic behavior of non-sqlite components running on a system since the variable is static.
Related issue: #656

Use setUseCaches instead of setDefaultUseCaches

---

src/main/java/org/sqlite/SQLiteErrorCode.java
src/main/java/org/sqlite/core/DB.java
src/test/java/org/sqlite/ErrorMessageTest.java

Helps in interpreting extended error codes which aren't included in the current `SQLiteErrorCode`.
In my case, allowed me to discover that
```
... org.sqlite.SQLiteException: [UNKNOWN_ERROR] unknown error (attempt to write a readonly database)
```
was really
```
... org.sqlite.SQLiteException: 0x608 (attempt to write a readonly database)
```
aka. `SQLITE_READONLY_DIRECTORY` because while my DB file was writable, the directory was not...

Show numeric code instead of `UNKNOWN_ERROR`

---

src/main/java/org/sqlite/jdbc3/JDBC3DatabaseMetaData.java
src/test/java/org/sqlite/DBMetaDataTest.java

* provide valid COLUMN_SIZE and DECIMAL_DIGITS values for columns queried using
Connection.getMetaData().getColumns(java.lang.String, java.lang.String, java.lang.String, java.lang.String)
* add/adjust unit tests to test this change
Fixes #733

fix: fix Connection.getMetaData().getColumns returns wrong/fixed values for column data type details (#733)

---

src/main/java/org/sqlite/core/CoreResultSet.java
src/main/java/org/sqlite/jdbc3/JDBC3ResultSet.java
src/main/java/org/sqlite/jdbc3/JDBC3Statement.java
src/test/java/org/sqlite/ResultSetTest.java

fix: empty result set should not be returned as closed

---

src/main/java/org/sqlite/SQLiteConnection.java
src/main/java/org/sqlite/SQLiteJDBCLoader.java
src/test/java/org/sqlite/SQLiteJDBCLoaderTest.java

This PR updates some code about file/path handling to use `java.nio` and Java 8 methods. It also uses a lazy directory stream for the cleanup of old native libs, which would close #198.

SQLiteJDBCLoader Java 8 and `java.nio` file/path operations

---

src/main/java/org/sqlite/jdbc3/JDBC3ResultSet.java
src/test/java/org/sqlite/RSMetaDataTest.java

changed isNullable() in JDBC3ResultSet to use first column of meta[checkCol(col)] as it returns [nullable, primary, auto_incremented]
added isPrimary() in JDBC3ResultSet to return the value of the second column of meta[checkCol(col)] added corresponding tests in RSMetaDataTest
corrected line 60 in columns test in RSMetaDataTest as a primary key attribute can be null in SQLite

correction of isNullable() in JDBC3ResultSet

---

src/main/java/org/sqlite/util/OSInfo.java
src/test/java/org/sqlite/util/OSInfoTest.java

If `isAndroid()` check fails, `checkIfAndroidTermux()` is called which runs `uname -o` command and check if its output contains `android`. This should fix #789. 
Sample command output in Termux before changes:
Sample command output in Termux after changes:

Allow correct recognition of Android OS when running Termux environment

---

CHANGELOG
NEWS.md
README.md
SQLiteJDBC.wiki
amalgamation_version.sh
src/main/ext/extension-functions.c
src/main/java/org/sqlite/Function.java
src/main/java/org/sqlite/ProgressHandler.java
src/main/java/org/sqlite/SQLiteConfig.java
src/main/java/org/sqlite/SQLiteConnection.java
src/main/java/org/sqlite/SQLiteDataSource.java
src/main/java/org/sqlite/SQLiteErrorCode.java
src/main/java/org/sqlite/SQLiteOpenMode.java
src/main/java/org/sqlite/core/DB.java
src/main/java/org/sqlite/jdbc3/JDBC3Connection.java
src/main/java/org/sqlite/jdbc3/JDBC3DatabaseMetaData.java
src/test/java/org/sqlite/JSON1Test.java

I think the more `https` the better.
1. Replaced `http://www.sqlite.org` with `https://www.sqlite.org`
2. Replaced `http://sqlite.org` with `https://www.sqlite.org`
3. Replaced `https://sqlite.org` with `https://www.sqlite.org`
4. Changed another http to https in Readme

links: use https for sqlite.org

---

src/main/java/org/sqlite/SQLiteConfig.java
src/test/java/org/sqlite/SQLiteConfigTest.java

I noticed while setting up the DataSource that the SQLiteConfig busyTimeout was getting out of synch with the busy_timeout pragma when doing something like the following:
```
final SQLiteDataSource ds = new SQLiteDataSource();
ds.getConfig().setBusyTimeout(2000);
```
This PR fixes this inconsistency. Note that it is still possible to set the pragma value directly and get out of synch, for example:
```
final SQLiteDataSource ds = new SQLiteDataSource();
ds.getConfig().setBusyTimeout(2000);
ds.getConfig().setPragma(Pragma.BUSY_TIMEOUT, "5000");
```
But, at least with this patch, you'd have to go out of your way to get out of synch, and for the normal usage, these values would now be kept in synch.
EDIT: added a second commit with a new test.

fix SQLiteConfig keep cached busyTimeout more consistent with busy_timeout pragma

---

src/main/java/org/sqlite/SQLiteDataSource.java
src/test/java/org/sqlite/SQLiteDataSourceTest.java

add SQLiteDataSource.setBusyTimeout(int milliseconds) so that we can do:
```
final SQLiteDataSource ds = new SQLiteDataSource();
ds.setBusyTimeout(1234);
```
instead of doing like below, or setting up a Properties object and providing it to the SQLiteDataSource constructor:
```
final SQLiteDataSource ds = new SQLiteDataSource();
ds.getConfig().setBusyTimeout(2000);
```
Note that the new test will fail because it depends on the change made by https://github.com/xerial/sqlite-jdbc/pull/843.
Without that fix, the line `assertThat(ds.getConfig().getBusyTimeout()).isEqualTo(1234);` in the new test will fail.

feat(SQLiteDataSource): add setBusyTimeout

---

src/main/java/org/sqlite/jdbc3/JDBC3DatabaseMetaData.java
src/test/java/org/sqlite/DBMetaDataTest.java

If columns are defined with `intvalue integer(5)`, `realvalue real(8,3)`, or `charvalue varchar(21)` for example, return `INTEGER`, `REAL` or `VARCHAR` respectively. This is consistent with how other JDBC drivers return the `TYPE_NAME` field in [`DatabaseMetaData.getColumns()`](https://docs.oracle.com/javase/8/docs/api/java/sql/DatabaseMetaData.html#getColumns-java.lang.String-java.lang.String-java.lang.String-java.lang.String-).
Tests are in https://github.com/xerial/sqlite-jdbc/blob/master/src/test/java/org/sqlite/DBMetaDataTest.java#L271

feat: remove length/ dimension of column data types in the `TYPE_NAME` field of `getColumns()`

---

src/main/java/org/sqlite/core/CoreStatement.java
src/main/java/org/sqlite/jdbc3/JDBC3PreparedStatement.java
src/test/java/org/sqlite/PrepStmtTest.java

Implements JDBC3PreparedStatement getParameterType and getParameterTypeName.
It returns the JDBC type based on the parameter class.

fix(jdbc): PreparedStatement getParameterType and getParameterTypeName

---

src/main/java/org/sqlite/core/CoreStatement.java
src/test/java/org/sqlite/PrepStmtTest.java

Before this commit, the code was failing with NPE when getParameterType was called before any PreparedStatement#setX was done.
Fix for #911

fix: Check parameters presence in getParameterType

---

src/main/java/org/sqlite/ExtendedCommand.java

Fixed the exception message when backup fails from "Restore failed" to "Backup failed"

fix: correct the exception message when backup fails

---

.github/workflows/ci.yml
pom.xml
src/main/java/org/sqlite/SQLiteJDBCLoader.java
src/main/java/org/sqlite/util/LibraryLoaderUtil.java

GraalVM 23.0.0 has been released.
This updates the CI to this version. This release should include https://github.com/oracle/graal/pull/5932 which enables the `native-exported` flow on unix and darwin systems.
The  `org.graalvm.sdk:graal-sdk` dependency in the pom is still set to `22.3.2`, the latest release is compiled with java 17 so that would force anyone using native-image to use at least a java 17 jdk.
Going forward, GraalVM releases will follow the latest LTR releases from java, so the next version (23.1.0) will likely require java 21.
This is still a draft as the CI will keep failing because the `graalvm/setup-graalvm` action does not support the latest release yet: https://github.com/graalvm/setup-graalvm/issues/45

ci: update to GraalVM 23

---

.github/workflows/ci.yml
pom.xml
src/main/java9/module-info.java

Update the native-image GitHub Actions flow to test against GraalVM 21 instead of GraalVM 20.
The change of the `org.graalvm.sdk:graal-sdk` to `org.graalvm.sdk:nativeimage` is a rename described here: https://www.graalvm.org/release-notes/JDK_21#refactoring-graalvm-sdk

ci: update native-image testing to GraalVM 21

---

pom.xml
src/main/java/org/sqlite/SQLiteJDBCLoader.java
src/main/java/org/sqlite/jdbc3/JDBC3DatabaseMetaData.java
src/main/java/org/sqlite/util/OSInfo.java
src/main/java9/org/sqlite/nativeimage/SqliteJdbcFeature.java

The logging framework (slf4j) should not be configured to be initialized at build-time:
* It is bad form to dictate native-image configuration for classes that are not our own. This can cause configuration conflicts if either the end-user or the maintainer of the external class have/add their own configuration.
* end-users often configure logging frameworks to either redirect to each other, or have custom formatting rules. Initializing the logging framework at build-time can cause this configuration to be missed and partially or completely ignored.
This PR makes sure the logging framework is again initialized at run-time, by:
* Using in-line declarations of single-use loggers: `org.sqlite.SQLiteJDBCLoader$VersionHolder`
* Creating a `LogHolder` subclass which holds the logger instance, if …

fix(native-image): do not initialize logging framework at build-time

---

src/main/java/org/sqlite/core/CoreStatement.java
src/main/java/org/sqlite/jdbc3/JDBC3DatabaseMetaData.java
src/main/java/org/sqlite/jdbc3/JDBC3PreparedStatement.java
src/main/java/org/sqlite/jdbc3/JDBC3Statement.java
src/test/java/org/sqlite/DBMetaDataTest.java
src/test/java/org/sqlite/PrepStmtTest.java
src/test/java/org/sqlite/StatementTest.java

Hello @gotson,
Over in https://github.com/xerial/sqlite-jdbc/issues/1018#issuecomment-1813516287 you mentioned that you'd be willing to look at a PR that restores getGeneratedKeys functionality if it could resolve the safety issues originally reported in #329. 
This PR seeks to do that by adding back support for Statement#getGeneratedKeys with a new implementation that tightly scopes the generated keys to the Statement object. This makes it safe to use in an interleaved manner, across threads, and with multiple Statements.
In the interest of transparency, this PR does not address tracking keys for multiple inserts on the same statement (#468). However, that functionality was never previously available. That it could potentially be added in future enhancements to this model if it became a …

feat(jdbc): reintroduce improved support for Statement#getGeneratedKeys

---

README.adoc
USAGE.md
demo/Sample.java

related #938.
- added try-with-resources to examples (README, USAGE and demo/Sample.java)
- changed exception handling to not ignore root causes
- removed finally blocks (not needed anymore)

Docs: Adding try-with-resources to examples and demo. related #938

---

src/main/java/org/sqlite/core/CoreStatement.java
src/test/java/org/sqlite/StatementTest.java

While profiling some software that makes heavy use of prepared statements and SQLite, I noticed that each call to `java.sql.Connection#prepareStatement(java.lang.String)` ended up compiling a regex pattern as part of `org.sqlite.core.CoreStatement.<init>(SQLiteConnection)` construction. This appears to be a recent addition as part of https://github.com/xerial/sqlite-jdbc/pull/1056  with example call trace showing up as over 75% of total allocations in JFR:
Because JDK `Pattern` instances are immutable and thread-safe, we can compile the regex on `CoreStatement` class load to a static field for reuse, and adjust the regex to avoid additional possible allocations from trimming and converting the SQL to lower case, as well as use non-capturing groups to avoid `Pattern#matcher` allocating the …

perf: CoreStatement uses optimize regex for generated key matches

---

.github/workflows/ci.yml
pom.xml

Changes:
* upgrade to 3.2.0 GPG plugin
* do NOT import key in home of runner (and leave it there once job done?)
* instead, make them both env variables
* and on CI force BC signer
This leaves GPG on workstation work unchanged.
Related to https://issues.apache.org/jira/browse/MGPG-90

build: use BC signer

---

pom.xml

The ArchUnit Junit5 TestEngine implementation is still initialized by the service loader to discover the available tests before building the native test binary. Removing the engine entirely for native-image tests resolves the issues and allows for removal of existing workarounds to exclude ArchUnit tests.
fixes #1097

build(deps): bump com.tngtech.archunit:archunit-junit5 from 1.2.1 to 1.3.0

---

src/main/java/org/sqlite/SQLiteConfig.java
src/test/java/org/sqlite/SQLiteConfigTest.java

This pull request fixes the bug described in #1123 .

fix: throw java.lang.ExceptionInInitializerError when calling SQLiteConfig.Pragma.values()

---

src/main/java/org/sqlite/jdbc3/JDBC3DatabaseMetaData.java
src/test/java/org/sqlite/DBMetaDataTest.java

Fixes #1132 - Generated columns with stored in SQLite are not marked as generated

fix(jdbc): generated columns with stored in SQLite are not marked as generated

---

src/main/java/org/sqlite/util/OSInfo.java

fix: never return arch as aarch64 when running in a 32-bit JVM

---

.github/workflows/ci.yml
pom.xml
src/main/java9/org/sqlite/nativeimage/SqliteJdbcFeature.java

GraalVM for JDK 22 [(release notes)](https://www.graalvm.org/release-notes/JDK_22/#native-image) enables the `--strict-image-heap` option by default, which requires all objects stored in the native-image heap to be marked as build-time initialized.
Issue can be reproduced on GraalVM for JDK 21 by adding `--strict-image-heap` as native-image cli argument. This is however not a future-proof testing setup as the option will be removed in a future GraalVM release. As form of validation, GraalVM for JDK 22 was added to the test suite.
Proof this does fix the issue:
* First commit adds GraalVM for JDK 22 to the test suite, which fails the suite on the reported `--initialize-at-build-time=org.sqlite.util.ProcessRunner` error.
* Second commit restores the CI to green.
fixes #1158

fix(native-image): add support for --strict-image-heap

---

README.adoc
pom.xml
src/main/java/org/sqlite/JDBC.java
src/main/java/org/sqlite/SQLiteJDBCLoader.java
src/main/java/org/sqlite/core/NativeDB.java
src/main/java/org/sqlite/jdbc3/JDBC3DatabaseMetaData.java
src/main/java/org/sqlite/jdbc3/JDBC3Statement.java
src/main/java/org/sqlite/util/Logger.java
src/main/java/org/sqlite/util/LoggerFactory.java
src/main/java/org/sqlite/util/OSInfo.java
src/test/java/org/sqlite/architecture/CodingRulesTest.java

In order to avoid the hard dependency on slf4j, this patch abstracts the Logger interface and LoggerFactory factory to fall back on a java.util.logging-based implementation if slf4j is not present.
Fixes #1094

feat: make slf4j optional with fallback on JUL

---

.github/workflows/ci.yml
pom.xml
src/test/resources/META-INF/native-image/org.xerial/sqlite-jdbc/reachability-metadata.json

* Test against GraalVM for JDK 24.
* Fix failures with JUnit 5.12 caused by missing build-time initialization.

Add JUnit 5.12 and GraalVM for JDK 24 support

---

src/main/java/org/sqlite/SQLiteConnection.java
src/test/java/org/sqlite/ConnectionTest.java

The side-effect consisted in temporarily creating a non-existing db-file to test for write-permission, see #1260
Also add some test to better document the expected behavior.

remove an undocumented side-effect from SQLiteConnection::open

---

src/main/java/org/sqlite/util/OSInfo.java

In a comment, update the link to Java bug #8005545, as the current one leads to a webpage saying: "This bug is not available."

OSInfo: Update link to Java bug #8005545

---

src/main/java/org/sqlite/jdbc3/JDBC3PreparedStatement.java
src/main/java/org/sqlite/jdbc4/JDBC4PreparedStatement.java
src/test/java/org/sqlite/PrepStmtTest.java

There are TODO markers in the JDBC4 Prepared Statement implementation relating to BLOB and CLOB data. These can easily be implemented by delegating to the existing JDBC implementations. This may not be optimised, but it will allow the use of CLOB and BLOB, which is a significant improvement.

Support JDBC4 CLOB and BLOB in PreparedStatement parameters
