xerial/sqlite-jdbc

src/main/java/org/sqlite/jdbc4/JDBC4Connection.java, src/main/java/org/sqlite/jdbc4/JDBC4PreparedStatement.java, src/main/java/org/sqlite/jdbc4/JDBC4ResultSet.java
This pull request throws SQLFeatureNotSupportedException from 4 methods on jdbc4.JDBC4Connection to be consistent with the JDBC API Javadoc, see issue #62
=> Throw exception on unsupported features

src/main/java/org/sqlite/jdbc4/JDBC4Connection.java, src/main/java/org/sqlite/jdbc4/JDBC4DatabaseMetaData.java, src/main/java/org/sqlite/jdbc4/JDBC4ResultSet.java, src/main/java/org/sqlite/jdbc4/JDBC4Statement.java
mostly useful on Connection instances but the rest is :scissors: as well
=> support JDBC 4 unwrap-ing

src/main/java/org/sqlite/core/CoreConnection.java, src/main/java/org/sqlite/jdbc4/JDBC4ResultSet.java, src/main/java/org/sqlite/jdbc4/JDBC4Statement.java, src/test/java/org/sqlite/StatementTest.java
+ missed unwrapping test for previous PR
=> support closeOnCompletion

Makefile, Makefile.common, src/main/ext/extension-functions.c, src/main/java/org/sqlite/core/NativeDB.c
Please look at the commit messages—they include plenty of explanation.
=> Building for new (released in 2016) and old SQLite versions

src/main/java/org/sqlite/core/DB.java, src/test/java/org/sqlite/QueryTest.java
=> Don't crash the JVM on null queries

src/main/java/org/sqlite/jdbc3/JDBC3DatabaseMetaData.java
=> Fixed NPE in getProcedureColumns

.travis.yml
Makes it possible to get Travis builds for PRs that change NativeDB.c pass.
=> Also build the JNI code in Travis builds

src/main/java/org/sqlite/core/NativeDB.c
This is a partial fix for https://bitbucket.org/xerial/sqlite-jdbc/issues/122/
The JVM does not crash anymore because of the native code, but the Java code is still not thread-safe.
=> Check whether the database or prepared statements have been closed

src/main/java/org/sqlite/SQLiteDataSource.java
setCouncChanges -> setCountChanges
setEnforceForeinKeys -> setEnforceForeignKeys
=> Fix typos in SQLiteDataSource public API.

src/main/java/org/sqlite/jdbc3/JDBC3PreparedStatement.java, src/test/java/org/sqlite/PrepStmtTest.java
Test case and proposed fix for #164
=> Check if pointer is valid before call to reset()

src/main/java/org/sqlite/jdbc4/JDBC4PreparedStatement.java
This enables support for closeOnCompletion for PreparedStatements via the parent Statement. Fixes #147
=> Add support for PreparedStatement#closeOnCompletion via simple Statement

src/main/java/org/sqlite/jdbc3/JDBC3ResultSet.java, src/test/java/org/sqlite/RSMetaDataTest.java
Fixed #116
Signed-off-by:doe300 <stadeldani@web.de>
=> ResultSetMetaData::getTableName now returns empty string

src/main/java/org/sqlite/jdbc3/JDBC3PreparedStatement.java
complete fix fro issue 74 add check valid pointer before reset in JDBC3PreparedStatement.java
=> issue 74 add check valid pointer before reset

src/main/java/org/sqlite/jdbc3/JDBC3ResultSet.java, src/test/java/org/sqlite/RSMetaDataTest.java
=> Adds support for TEXT column_type

src/main/java/org/sqlite/core/CoreResultSet.java, src/test/java/org/sqlite/ConnectionTest.java
=> Fix concurrent issue in CoreResultSet closing

src/main/java/org/sqlite/jdbc3/JDBC3DatabaseMetaData.java, src/test/java/org/sqlite/DBMetaDataTest.java
=> Fix ORDINAL_POSITION in DatabaseMetaData#getColumns

src/main/java/org/sqlite/jdbc3/JDBC3DatabaseMetaData.java, src/test/java/org/sqlite/DBMetaDataTest.java
=> Fix issue #239: getPrimaryKeys for views

Makefile, docker/dockcross-arm64, src/main/java/org/sqlite/util/OSInfo.java
=> Add support for aarch64 (arm64)

src/main/java/org/sqlite/jdbc4/JDBC4DatabaseMetaData.java
DatabaseMetaData throws SQLFeatureNotSupportedException for unimplemented JDBC 4 features -fixes #255
=> DatabaseMetaData throws SQLFeatureNotSupportedException for unimplemented JDBC 4 features -fixes #255

src/main/java/org/sqlite/SQLiteConfig.java
Fixed SQLiteConfig class, setTempStore() method javadoc - fixes #257
=> Fixed SQLiteConfig class, setTempStore() method javadoc - fixes #257

README.md
=> update README - Hint for maven-shade-plugin

src/main/java/org/sqlite/jdbc3/JDBC3Connection.java, src/test/java/org/sqlite/TypeMapTest.java
Based on the comment of illumi in the closed issue https://github.com/xerial/sqlite-jdbc/pull/184 I changed the code and added a test.
=> fix regarding https://github.com/xerial/sqlite-jdbc/pull/184

src/main/java/org/sqlite/SQLiteJDBCLoader.java
=> Fix for issue #269

src/main/java/org/sqlite/jdbc3/JDBC3DatabaseMetaData.java, src/test/java/org/sqlite/DBMetaDataTest.java
DatabaseMetaData getImportedKeys does not return primary keys or foreign key names #280
=> DatabaseMetaData getImportedKeys does not return primary keys or foreign key names #280

src/main/java/org/sqlite/jdbc3/JDBC3DatabaseMetaData.java, src/test/java/org/sqlite/DBMetaDataTest.java
DatabaseMetaData getImportedKeys does not return primary keys or foreign key names bug - #280
=> DatabaseMetaData getImportedKeys does not return primary keys or foreign key names bug - #280

src/main/java/org/sqlite/jdbc3/JDBC3DatabaseMetaData.java, src/main/java/org/sqlite/jdbc4/JDBC4ResultSet.java, src/test/java/org/sqlite/DBMetaDataTest.java
DatabaseMetaData getImportedKeys does not return primary keys or foreign key names bug - #280
=> DatabaseMetaData getImportedKeys does not return primary keys or foreign key names bug - #280 

src/main/java/org/sqlite/jdbc3/JDBC3DatabaseMetaData.java, src/main/java/org/sqlite/jdbc4/JDBC4ResultSet.java, src/test/java/org/sqlite/DBMetaDataTest.java
Feature request: DatabaseMetadata to distinguish user table from system table enhancement
- fixes #283
=> Feature request: DatabaseMetadata to distinguish user table from system table enhancement - fixes #283

src/main/java/org/sqlite/SQLiteConfig.java
Quick addition of an APPLICATION_ID pragma and convience function setApplicationId(int) (similar to USER_VERSION). Closes #292
=> Add Pragma.APPLICATION_ID and setApplication convenience function closes #292

src/main/java/org/sqlite/core/CorePreparedStatement.java, src/main/java/org/sqlite/jdbc3/JDBC3PreparedStatement.java, src/test/java/org/sqlite/QueryTest.java
According to jdbc specification driver should take into account time zone from calendar.
=> take into account the calendar in the prepared statement

src/main/java/org/sqlite/core/DB.java
=> Don't close prepared statements on constraint violation (Fixes #74)

src/main/java/org/sqlite/core/CoreStatement.java
=> Fixed exception during finalize when statement AND db is already closed

Makefile
Compilers moved outside of $PATH, thus CROSS_PREFIX has to be adjusted.
=> Fix build with current version of dockcross

docker/dockcross-android-arm, docker/dockcross-arm64, docker/dockcross-armv5, docker/dockcross-armv6, docker/dockcross-armv7, docker/dockcross-ppc64, docker/dockcross-windows-x64, docker/dockcross-windows-x86
References: https://github.com/dockcross/dockcross/pull/265
=> Fix dockercross build error "docker: invalid reference format" when user or group contains spaces

src/main/java/org/sqlite/jdbc3/JDBC3PreparedStatement.java, src/test/java/org/sqlite/PrepStmtTest.java
Fix #365  and remove an unused local variable in PrepStmtTest.
=> Fix prep stmt test

src/main/java/org/sqlite/jdbc3/JDBC3PreparedStatement.java, src/test/java/org/sqlite/PrepStmtTest.java
Fix #363 and add corresponding unit tests.
=> Prevent null dates in prepared statements

src/main/java/org/sqlite/jdbc3/JDBC3ResultSet.java
=> Fix NPE in JDBC3ResultSet.getCharacterStream

README.md
* Add News entry for 3.25.2 release.
* Fix some SQLite version links.
* Fix some typos.
=> Fix some README stuff

src/main/java/org/sqlite/core/DB.java
https://github.com/xerial/sqlite-jdbc/issues/385
=> #385 Fix the params check when vals array is reused

src/main/java/org/sqlite/Function.java, src/main/java/org/sqlite/core/NativeDB.c, src/test/java/org/sqlite/UDFTest.java
This exposes another base class Function.Window alongside Function.Aggregate that allows implementing a user-defined window function using the new support introduced in SQLite 3.25
=> Add support for user-defined window functions

src/main/java/org/sqlite/jdbc3/JDBC3DatabaseMetaData.java, src/test/java/org/sqlite/DBMetaDataTest.java
=> Fix getPrimaryKeys() to work with single unnamed primary key

src/main/java/org/sqlite/jdbc3/JDBC3ResultSet.java
Fixes #403 by defaulting the type affinity to NUMERIC instead of NULL
=> Corrects type affinity (#403)

src/main/java/org/sqlite/jdbc3/JDBC3DatabaseMetaData.java, src/test/java/org/sqlite/DBMetaDataTest.java
column (#400)
- Modification in JDBC3DatabaseMetaData
- Adding a UnitTest to DBMetaDataTest
=> Add support for getImportedKeys with ForeignKeys over more then one (#400)

Makefile
By passing `SQLITE_OBJ=/path/to/libsqlite3.a` and `SQLITE_HEADER=/path/to/sqlite3.h`
one can circumvent SQLite to be downloaded and custom compiled.
Users can have SQLite globally installed, reusing that for JDBC driver instead
of having a version deviating from the rest of the system.
This closes #464
=> Add suport for external archive amalgamation (#464)

src/main/java/org/sqlite/SQLiteConfig.java
Just general code hygiene since you're already using a VCS to keep code around.
=> Remove commented out code

src/main/java/org/sqlite/jdbc3/JDBC3DatabaseMetaData.java
Changed sqlite system table mask.
=> 427: wrong masking of sqlite system tables

src/main/java/org/sqlite/SQLiteCommitListener.java, src/main/java/org/sqlite/SQLiteConnection.java, src/main/java/org/sqlite/SQLiteUpdateListener.java, src/main/java/org/sqlite/core/DB.java, src/main/java/org/sqlite/core/NativeDB.c, src/main/java/org/sqlite/core/NativeDB.java, src/test/java/org/sqlite/ListenerTest.java
Add support for update/commit/rollback event callbacks. I'm not including the updated shared libraries in this PR, since I figured you all would want to build them yourselves.
Fixes #98
=> Add support for update/commit/rollback event notifications

Makefile.common, src/test/java/org/sqlite/SQLiteDataSourceTest.java
These commits make it flawlessly compile on HP-UX for me. All tests pass.
=> Add support for HP-UX IA64N

src/main/java/org/sqlite/SQLiteJDBCLoader.java
If all else fails use `java.library.path` and try all of the included dirs to load this library.
Works for me on Windows 10, FreeBSD 12-STABLE and HP-UX 11.31.
@lapo-luchini This is interesting also for the FreeBSD port.
=> Cannot load native library from java.library.path (#462)

src/main/java/org/sqlite/SQLiteConfig.java, src/test/java/org/sqlite/ReadUncommittedTest.java
=> Fix typo of READ_UNCOMMITED to READ_UNCOMMITTED

src/main/java/org/sqlite/jdbc4/JDBC4PreparedStatement.java
Hi
I have change some code for debug better tthe SQL:
Override ToString() for show PreparedStament SQL and parameters
Thanks
=> Override ToString() for show PreparedStament SQL and parameters

src/main/java/org/sqlite/ExtendedCommand.java, src/main/java/org/sqlite/core/NativeDB.c
support backup/restore with URI filename see https://sqlite.org/uri.html
=> backup/restore use sqlite3_open_v2

Usage.md
=> fix comment

docker/dockcross-android-arm, docker/dockcross-arm64, docker/dockcross-armv5, docker/dockcross-armv6, docker/dockcross-armv7, docker/dockcross-armv7a, docker/dockcross-ppc64, docker/dockcross-windows-x64, docker/dockcross-windows-x86
Dockcross scripts installed locally have been updated using `./docker/dockcross-<xxx> update`
=> update all dockcross scripts via dockcross-xxx update

src/main/java/org/sqlite/SQLiteConnection.java
=> Fix file descriptor (handle) leak when opening database fails

.github/workflows/test.yml
Build on jdk 17 instead of 16.
Shouls help to close #729
=> ci: build on jdk 17

README.md
Mostly copied from Release descriptions, although I added a few things for 3.35.0.1 that I happened to see in the diff.
=> Update changelog for 3.35.0.1 through 3.36.0.3

Makefile
Instead of relying of changing ifdefs use the variable decralation as anchor.
This fixes #760
=> Properly add JDBC_EXTENSIONS pragma (#760)

src/main/java/org/sqlite/SQLiteConfig.java, src/main/java/org/sqlite/SQLiteDataSource.java
Added support for legacy alter table flag
More info [here](https://www.sqlite.org/pragma.html#pragma_legacy_alter_table)
=> Added support for legacy alter table flag

Makefile, Makefile.common, pom.xml, src/main/java/org/sqlite/JDBC.java, src/main/java/org/sqlite/SQLiteJDBCLoader.java, src/main/java/org/sqlite/core/NativeDB.java, src/main/java/org/sqlite/jdbc3/JDBC3DatabaseMetaData.java, src/main/java/org/sqlite/jdbc3/JDBC3Statement.java, src/main/java/org/sqlite/util/OSInfo.java
=> fix: downgrade SLF4J to 1.7

src/main/java/org/sqlite/jdbc3/JDBC3ResultSet.java, src/test/java/org/sqlite/PrepStmtTest.java
=> fix: avoid double precision in getBigDecimal

src/main/java/org/sqlite/core/CoreStatement.java, src/test/java/org/sqlite/StatementTest.java
This pull request improves `getGeneratedKeys` to support SQL statements that:
1. have a [CTE](https://www.sqlite.org/lang_with.html) preceding the `INSERT` (e.g. `WITH cte AS (SELECT 1 AS a) INSERT INTO t1(a) SELECT a FROM cte`)
2. use the more esoteric [`REPLACE`](https://www.sqlite.org/lang_insert.html) keyword instead of `INSERT OR REPLACE` (which SQLite supports for MySQL compatibility)
The improved matching will catch these cases and ensure that `genGeneratedKeys` returns an appropriate result set for them.
The tests are also expanded to cover the greater range of statement varieties.
=> fix(jdbc): support CTE and REPLACE syntax with Statement#getGeneratedKeys

README.adoc
https://github.com/xerial/sqlite-jdbc/issues/1049 requested a PR to add the signing key to the README.  This is that PR.
=> docs: add gpg key to README

pom.xml
Reverts xerial/sqlite-jdbc#1079
Refs: 3b837607351bc1bfd99e26e755a1bd485fac4575
=> revert(deps): bump org.apache.maven.plugins:maven-gpg-plugin from 3.1.0 to 3.2.0

README.adoc, demo/Sample.java
cf. AutoCloseable (Java SE 21 & JDK 21)
https://docs.oracle.com/en%2Fjava%2Fjavase%2F21%2Fdocs%2Fapi%2F%2F/java.base/java/lang/AutoCloseable.html
=> style: fix typos in comment

USAGE.md, src/main/java/org/sqlite/SQLiteConfig.java, src/main/java/org/sqlite/SQLiteConnectionConfig.java, src/main/java/org/sqlite/core/CoreStatement.java, src/test/java/org/sqlite/PrepStmtTest.java, src/test/java/org/sqlite/StatementTest.java
=> feat(jdbc): add configuration to disable eager retrieval of generated keys
